version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00" # 3:00 PM UTC = 8:00 PM PKT
      timezone: "Asia/Karachi"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"