name: Continuous Integration
on:
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies from package-lock.json
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run linting to check code quality
      - name: Run Linting
        run: npm run lint || echo "No Lint Script Defined"

      # Step 5: Run tests (optional)
      - name: Run Tests
        run: npm test || echo "No Test Script Defined"

      # Step 6: Upload test or lint reports as artifacts
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            reports/
            coverage/
